# Generated by Django 4.1 on 2022-11-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studio",
            name="location",
        ),
        migrations.AddField(
            model_name="studio",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="studio",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="studio",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="studio",
            name="postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studio",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
