# Generated by Django 4.1 on 2022-11-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="curr_capacity",
        ),
        migrations.AddField(
            model_name="event",
            name="curr_capacity",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
