# Generated by Django 4.1 on 2022-11-16 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amenities",
                to="studios.studio",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="studio",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="studios.studio",
            ),
        ),
        migrations.AlterField(
            model_name="studioimage",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="studios.studio",
            ),
        ),
    ]
