# Generated by Django 4.1 on 2022-11-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_remove_class_curr_capacity_event_curr_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='curr_capacity',
            new_name='curr_size',
        ),
    ]
