# Generated by Django 4.1 on 2022-11-16 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 7, 11, 35, 826346, tzinfo=datetime.timezone.utc)),
        ),
    ]
