# Generated by Django 4.1 on 2022-11-16 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 7, 25, 19, 131708, tzinfo=datetime.timezone.utc)),
        ),
    ]
