# Generated by Django 4.1 on 2022-11-16 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 23, 51, 26, 294692, tzinfo=datetime.timezone.utc)),
        ),
    ]
