# Generated by Django 4.1 on 2022-12-07 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_payment_subscription_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='active_subscription',
            field=models.DateTimeField(default=datetime.datetime(1922, 12, 7, 18, 42, 10, 498396)),
        ),
    ]
