# Generated by Django 4.1 on 2022-11-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fcuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcuser',
            name='password2',
        ),
    ]
