# Generated by Django 4.1 on 2022-12-08 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_fcuser_active_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='active_subscription',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
