# Generated by Django 4.1 on 2022-12-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_fcuser_active_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_info',
            field=models.CharField(default='****-****-****-****', max_length=50),
        ),
    ]
