# Generated by Django 4.1 on 2022-11-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_fcuser_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
