# Generated by Django 4.1 on 2022-11-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
