# Generated by Django 4.1 on 2022-11-17 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_fcuser_email_alter_fcuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(default=datetime.date(2022, 11, 17)),
        ),
    ]
