# Generated by Django 4.1 on 2022-11-17 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
