# Generated by Django 4.1 on 2022-11-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_alter_amenity_studio_alter_event_studio_and_more'),
        ('accounts', '0015_alter_fcuser_active_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='history',
            field=models.ManyToManyField(related_name='history_events', to='studios.event'),
        ),
        migrations.AddField(
            model_name='fcuser',
            name='schedule',
            field=models.ManyToManyField(related_name='schedule_events', to='studios.event'),
        ),
    ]
