# Generated by Django 4.1 on 2022-11-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_fcuser_history_fcuser_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='active_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
